[vars]
fonts-version="2.7.5"

[report]
http-ignore = ["http://support.anychart.com", "http://phantomjs.org", "http://www.graphicsjs.org", "http://6.anychart.com"]

[redirect]
redirects = """
/7.1.1/Axes_Grid_Scales_Trends_etc/Axis_Scale >> /7.1.1/Axes_Grid_Scales_Trends_etc/Scales
/Basic_Charts_Types/Area_Chart >> /Basic_Charts/Area_Chart
/Basic_Charts_Types/Bar_Chart >> /Basic_Charts/Bar_Chart
/Basic_Charts_Types/Box_Chart >> /Basic_Charts/Box_Chart
/Basic_Charts_Types/Bubble_Chart >> /Basic_Charts/Bubble_Chart
/Basic_Charts_Types/Bullet_Chart >> /Basic_Charts/Bullet_Chart
/Basic_Charts_Types/Column_Chart >> /Basic_Charts/Column_Chart
/Basic_Charts_Types/Error_Chart >> /Basic_Charts/Error_Chart
/Basic_Charts_Types/Funnel_Chart >> /Basic_Charts/Funnel_Chart
/Basic_Charts_Types/Heat_Map_Chart >> /Basic_Charts/Heat_Map_Chart
/Basic_Charts_Types/Japanese_Candlestick_Chart >> /Basic_Charts/Japanese_Candlestick_Chart
/Basic_Charts_Types/Line-Spline-StepLine_Charts >> /Basic_Charts/Line_Chart
/Basic_Charts_Types/Marker_Chart >> /Basic_Charts/Marker_Chart
/Basic_Charts_Types/OHLC_Chart >> /Basic_Charts/OHLC_Chart
/Basic_Charts_Types/Percent_Stacked_Area-SplineArea_Charts >> /Basic_Charts/Stacked/Overview
/Basic_Charts_Types/Percent_Stacked_Bar-Column_Charts >> /Basic_Charts/Stacked/Overview
/Basic_Charts_Types/Pie-Doughnut_Charts >> /Basic_Charts/Pie_Chart
/Basic_Charts_Types/Polar_Chart >> /Basic_Charts/Polar_Plot/Overview
/Basic_Charts_Types/Pyramid_Chart >> /Basic_Charts/Pyramid_Chart
/Basic_Charts_Types/Radar_Chart >> /Basic_Charts/Radar_Plot/Overview
/Basic_Charts_Types/Range_Area-SplineArea_Charts >> /Basic_Charts/
/Basic_Charts_Types/Range_Bar-Column_Charts >> /Basic_Charts/
/Basic_Charts_Types/Scatter_Chart >> /Basic_Charts/Scatter_Plot/Overview
/Basic_Charts_Types/Sparkline_Chart >> /Basic_Charts/Sparkline_Chart
/Basic_Charts_Types/Stacked_Area-SplineArea_Charts >> /Basic_Charts/Stacked/Overview
/Basic_Charts_Types/Stacked_Bar-Column_Charts >> /Basic_Charts/Stacked/Overview
/Basic_Charts_Types/TreeMap_Chart >> /Basic_Charts/TreeMap_Chart
/Basic_Charts_Types/3D_Charts >> /Basic_Charts/3D/Overview
/7.13.0/Basic_Charts_Types/Area_Chart >> /Basic_Charts/Area_Chart
/7.13.0/Basic_Charts_Types/Bar_Chart >> /Basic_Charts/Bar_Chart
/7.13.0/Basic_Charts_Types/Box_Chart >> /Basic_Charts/Box_Chart
/7.13.0/Basic_Charts_Types/Bubble_Chart >> /Basic_Charts/Bubble_Chart
/7.13.0/Basic_Charts_Types/Bullet_Chart >> /Basic_Charts/Bullet_Chart
/7.13.0/Basic_Charts_Types/Column_Chart >> /Basic_Charts/Column_Chart
/7.13.0/Basic_Charts_Types/Error_Chart >> /Basic_Charts/Error_Chart
/7.13.0/Basic_Charts_Types/Funnel_Chart >> /Basic_Charts/Funnel_Chart
/7.13.0/Basic_Charts_Types/Heat_Map_Chart >> /Basic_Charts/Heat_Map_Chart
/7.13.0/Basic_Charts_Types/Japanese_Candlestick_Chart >> /Basic_Charts/Japanese_Candlestick_Chart
/7.13.0/Basic_Charts_Types/Line-Spline-StepLine_Charts >> /Basic_Charts/Line_Chart
/7.13.0/Basic_Charts_Types/Marker_Chart >> /Basic_Charts/Marker_Chart
/7.13.0/Basic_Charts_Types/OHLC_Chart >> /Basic_Charts/OHLC_Chart
/7.13.0/Basic_Charts_Types/Percent_Stacked_Area-SplineArea_Charts >> /Basic_Charts/Stacked/Overview
/7.13.0/Basic_Charts_Types/Percent_Stacked_Bar-Column_Charts >> /Basic_Charts/Stacked/Overview
/7.13.0/Basic_Charts_Types/Pie-Doughnut_Charts >> /Basic_Charts/Pie_Chart
/7.13.0/Basic_Charts_Types/Polar_Chart >> /Basic_Charts/Polar_Plot/Overview
/7.13.0/Basic_Charts_Types/Pyramid_Chart >> /Basic_Charts/Pyramid_Chart
/7.13.0/Basic_Charts_Types/Radar_Chart >> /Basic_Charts/Radar_Plot/Overview
/7.13.0/Basic_Charts_Types/Range_Area-SplineArea_Charts >> /Basic_Charts/
/7.13.0/Basic_Charts_Types/Range_Bar-Column_Charts >> /Basic_Charts/
/7.13.0/Basic_Charts_Types/Scatter_Chart >> /Basic_Charts/Scatter_Plot/Overview
/7.13.0/Basic_Charts_Types/Sparkline_Chart >> /Basic_Charts/Sparkline_Chart
/7.13.0/Basic_Charts_Types/Stacked_Area-SplineArea_Charts >> /Basic_Charts/Stacked/Overview
/7.13.0/Basic_Charts_Types/Stacked_Bar-Column_Charts >> /Basic_Charts/Stacked/Overview
/7.13.0/Basic_Charts_Types/TreeMap_Chart >> /Basic_Charts/TreeMap_Chart
/7.13.0/Basic_Charts_Types/3D_Charts >> /Basic_Charts/3D/Overview
"""

